// Hyperscaler Hub: base map for module 5 (sites). One-off generator, not part of the scheduled refresh: run it only to
// change the map geometry. Needs the npm packages world-atlas@2, us-atlas@3, topojson-client@3, topojson-simplify@3 and
// d3-geo@3 (install them in a scratch folder and run with NODE_PATH pointing there):
//   NODE_PATH=/tmp/mapgen/node_modules node scripts/hyperscalers/build-map.mjs
// Writes site/hiperescaladores/assets/map-data.js (window.HYP_MAP): pre-projected SVG paths for two views and the
// projection parameters the page uses to place sites (North America: conic equal-area, parallels 29.5/45.5, rotated
// 96°W; world: equirectangular). Sources: Natural Earth via world-atlas (countries-50m, countries-110m); U.S. Census
// Bureau cartographic boundaries via us-atlas (states-10m).
import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
const require = createRequire(process.env.NODE_PATH + '/');
const topo = require('topojson-client');
const simp = require('topojson-simplify');
const d3 = require('d3-geo');
const w50raw = simp.presimplify(require('world-atlas/countries-50m.json'));
const w50 = simp.simplify(w50raw, simp.quantile(w50raw, 0.35));
const w110 = require('world-atlas/countries-110m.json');
const us = require('us-atlas/states-10m.json');
const r1 = (s) => s.replace(/(\d+\.\d)\d+/g, '$1');

// North America
const W = 960, H = 600;
const na = d3.geoConicEqualArea().parallels([29.5, 45.5]).rotate([96, 0]).center([0, 0]);
na.fitExtent([[8, 8], [W - 8, H - 8]], { type: 'MultiPoint', coordinates: [[-127, 25], [-66, 25], [-127, 57], [-66, 57], [-96, 58.5], [-96, 24]] });
na.clipExtent([[0, 0], [W, H]]);
const pNA = d3.geoPath(na);
const countries50 = topo.feature(w50, w50.objects.countries).features.filter((f) => ['124', '840', '484', '192', '044', '388', '332', '214', '630', '320', '084', '304'].includes(String(f.id).padStart(3, '0')));
const usP = simp.presimplify(us);
const usS = simp.simplify(usP, simp.quantile(usP, 0.25));
const states = topo.mesh(usS, usS.objects.states, (a, b) => a !== b);
const naPaths = { land: r1(countries50.map((f) => pNA(f)).filter(Boolean).join('')), borders: r1(pNA(topo.mesh(w50, w50.objects.countries, (a, b) => a !== b)) || ''), states: r1(pNA(states) || '') };

// World
const WW = 960, WH = 470;
const wp = d3.geoEquirectangular();
wp.fitExtent([[4, 4], [WW - 4, WH - 4]], { type: 'MultiPoint', coordinates: [[-180, 78], [180, 78], [-180, -50], [180, -50]] });
wp.clipExtent([[0, 0], [WW, WH]]);
const pW = d3.geoPath(wp);
const land110 = topo.feature(w110, w110.objects.countries).features.filter((f) => String(f.id) !== '010');
const worldPaths = { land: r1(land110.map((f) => pW(f)).filter(Boolean).join('')), borders: r1(pW(topo.mesh(w110, w110.objects.countries, (a, b) => a !== b)) || '') };

// self-check of the page's projection formulas against d3
const P = { na: { k: na.scale(), t: na.translate(), par: [29.5, 45.5], rot: 96 }, world: { k: wp.scale(), t: wp.translate() } };
function fNA(lon, lat) {
  const rad = Math.PI / 180, p0 = P.na.par[0] * rad, p1 = P.na.par[1] * rad, n = (Math.sin(p0) + Math.sin(p1)) / 2, C = Math.cos(p0) ** 2 + 2 * n * Math.sin(p0);
  const l = (lon + P.na.rot) * rad, rho = Math.sqrt(C - 2 * n * Math.sin(lat * rad)) / n, rho0 = Math.sqrt(C) / n;
  return [P.na.t[0] + P.na.k * rho * Math.sin(n * l), P.na.t[1] - P.na.k * (rho0 - rho * Math.cos(n * l))];
}
const fW = (lon, lat) => [P.world.t[0] + P.world.k * lon * Math.PI / 180, P.world.t[1] - P.world.k * lat * Math.PI / 180];
for (const [lo, la] of [[-100.2, 34.43], [-123.09, 55.34], [-74.5, 40.1]]) { const a = na([lo, la]), b = fNA(lo, la); if (Math.hypot(a[0] - b[0], a[1] - b[1]) > 0.5) throw new Error(`NA projection mismatch at ${lo},${la}: ${a} vs ${b}`); }
for (const [lo, la] of [[26, 64], [135.8, -30.1]]) { const a = wp([lo, la]), b = fW(lo, la); if (Math.hypot(a[0] - b[0], a[1] - b[1]) > 0.5) throw new Error('world projection mismatch'); }

const out = { source: 'Natural Earth via world-atlas (countries-50m, countries-110m); U.S. Census Bureau cartographic boundaries via us-atlas (states-10m, simplified)', na: { w: W, h: H, proj: P.na, ...naPaths }, world: { w: WW, h: WH, proj: P.world, ...worldPaths } };
await writeFile('site/hiperescaladores/assets/map-data.js', `// Base map for the Hyperscaler Hub sites module. Generated by scripts/hyperscalers/build-map.mjs — do not hand-edit.\n// ${out.source}.\nwindow.HYP_MAP = ${JSON.stringify(out)};\n`);
console.log('map-data.js', Math.round(JSON.stringify(out).length / 1024), 'KB');
