// Pulls the fast-moving Banxico series (policy rate, FIX exchange rate, international reserves,
// TIIE, Cetes, UDI, monetary base) from Banco de México's SIE REST API and writes
// site/mx/fiscal/data.js as `window.LIVE_DATA_MX = {...}`.
//
// The SIE API needs a free token (https://www.banxico.org.mx/SieAPIRest/service/v1/token),
// supplied as the BANXICO_TOKEN environment variable (a GitHub Actions secret in CI).
// Docs: https://www.banxico.org.mx/SieAPIRest/service/v1/doc/consultaDatosSerieOp
//
// This script intentionally does NOT touch the SHCP public-finance figures (SHRFSP, revenue,
// spending, holders) — those come from SHCP's monthly release and are refreshed on a separate,
// monthly cadence via a reviewed PR to site/mx/fiscal/monthly-data.js.
//
// Runs on GitHub Actions' ubuntu-latest runner (Node 20+, global fetch). No npm install needed.

const OUT_PATH = new URL('../site/mx/fiscal/data.js', import.meta.url);
const TOKEN = process.env.BANXICO_TOKEN;

// Series catalogue: https://www.banxico.org.mx/SieAPIRest/service/v1/doc/catalogoSeries
// The response carries each series' official title, which is logged on every run so a wrong
// ID is caught immediately (see `titulo` in the log).
const SERIES = {
  tasaObjetivo: { id: 'SF61745', desc: 'Tasa objetivo, % anual' },
  fix:          { id: 'SF43718', desc: 'Tipo de cambio FIX, pesos por dólar' },
  reservas:     { id: 'SF43707', desc: 'Reservas internacionales, millones de dólares (semanal)' },
  tiie28:       { id: 'SF43783', desc: 'TIIE a 28 días, % anual' },
  cetes28:      { id: 'SF43936', desc: 'Cetes a 28 días, tasa de rendimiento en subasta primaria, %' },
  cetes364:     { id: 'SF43939', desc: 'Cetes a 364 días, tasa de rendimiento en subasta primaria, %' },
  udi:          { id: 'SP68257', desc: 'Valor de la UDI, pesos' },
  // Monetary base (weekly, millions of pesos). Set BANXICO_SERIES_BASE_MONETARIA to override if
  // the catalogue ID differs; the run log prints the title returned by the API for verification.
  baseMonetaria:{ id: process.env.BANXICO_SERIES_BASE_MONETARIA || 'SF30579', desc: 'Base monetaria, millones de pesos (semanal)' },
};

// Banxico dates arrive as "dd/mm/yyyy"; normalise to ISO so the page's string-only date
// formatting (no Date objects, no timezone shifts) works unchanged.
function toISO(dmy) {
  const [d, m, y] = dmy.split('/');
  return `${y}-${m}-${d}`;
}

async function fetchOportuno(ids) {
  const url = `https://www.banxico.org.mx/SieAPIRest/service/v1/series/${ids.join(',')}/datos/oportuno?token=${encodeURIComponent(TOKEN)}`;
  const res = await fetch(url, { headers: { 'Accept': 'application/json', 'User-Agent': 'fnam-debt-monitor-bot/1.0' } });
  if (!res.ok) throw new Error(`Banxico SIE -> HTTP ${res.status} ${await res.text().catch(() => '')}`);
  const j = await res.json();
  const out = {};
  for (const s of (j.bmx && j.bmx.series) || []) {
    const d = (s.datos || [])[0];
    const raw = d ? String(d.dato).replace(/,/g, '') : '';
    const val = raw && raw !== 'N/E' ? Number(raw) : NaN;
    out[s.idSerie] = { titulo: s.titulo, date: d ? toISO(d.fecha) : null, value: Number.isFinite(val) ? val : null };
  }
  return out;
}

async function main() {
  if (!TOKEN) {
    console.error('BANXICO_TOKEN is not set — nothing fetched, data.js left unchanged.');
    process.exit(1);
  }
  const keys = Object.keys(SERIES);
  const ids = keys.map((k) => SERIES[k].id);
  let bySeries = {};
  try {
    bySeries = await fetchOportuno(ids);
  } catch (e) {
    // One bad ID can fail the whole multi-series call, so fall back to one request per series.
    console.warn('Batch request failed, retrying series one by one:', e.message);
    for (const id of ids) {
      try { Object.assign(bySeries, await fetchOportuno([id])); }
      catch (e2) { console.warn(`${id}: ${e2.message}`); }
    }
  }

  const payload = { generatedAt: new Date().toISOString() };
  const errors = [];
  for (const k of keys) {
    const s = bySeries[SERIES[k].id];
    if (s && s.value != null) {
      payload[k] = { date: s.date, value: s.value, series: SERIES[k].id };
      console.log(`${k.padEnd(14)} ${SERIES[k].id}  ${s.date}  ${s.value}  «${s.titulo}»`);
    } else {
      payload[k] = null;
      errors.push(`${k} (${SERIES[k].id}): ${s ? 'no numeric value' : 'not returned'}`);
    }
  }
  if (errors.length) console.warn('Some series failed to fetch (page keeps its previous value for those):\n' + errors.join('\n'));
  if (keys.every((k) => payload[k] === null)) throw new Error('Every series failed — refusing to overwrite data.js');

  const js = `// AUTO-GENERATED by scripts/fetch-mx-data.mjs — do not hand-edit.
// Last refreshed: ${payload.generatedAt}
// Each field is {date, value} from the Banxico SIE API. If a series failed to fetch on the most
// recent run it is null here and site/mx/fiscal/index.html keeps its last baked-in value for it.
window.LIVE_DATA_MX = ${JSON.stringify(payload, null, 2)};
`;
  await import('node:fs/promises').then((fs) => fs.writeFile(OUT_PATH, js, 'utf8'));
  console.log('Wrote', OUT_PATH.pathname);
}

main().catch((e) => { console.error(e); process.exit(1); });
