#!/usr/bin/env python3
"""Generates site/<company>/index.html for the airport-group models (ASUR, OMA) from the GAP page.

The GAP page (site/gap/index.html) is the design reference: its CSS and section skeleton are reused verbatim;
company-specific text (titles, section descriptions, the special-situation and explainer sections, sources) is
substituted from the COMPANIES table below. Run after editing either input:  python3 tools/airports/make-site.py
"""
import re, os, sys
ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
gap = open(os.path.join(ROOT, 'site', 'gap', 'index.html'), encoding='utf-8').read()

def bi(es, en):
    return f'<span class="es">{es}</span><span class="en" hidden>{en}</span>'

COMPANIES = {
  'asur': {
    'prefix': 'ASUR', 'short': 'ASUR', 'name': 'Grupo Aeroportuario del Sureste', 'title_es': 'ASUR · Modelo financiero interactivo | Grupo Aeroportuario del Sureste',
    'desc_es': 'Modelo financiero interactivo de Grupo Aeroportuario del Sureste (ASUR): estados financieros comparables por trimestre, tráfico de pasajeros en México, Puerto Rico y Colombia, acción, DCF y valuación relativa. Datos públicos.',
    'eyebrow_es': 'Modelo financiero interactivo · Datos públicos (BMV / NYSE / SEC)', 'eyebrow_en': 'Interactive financial model · Public data (BMV / NYSE / SEC)',
    'listing_home': 'ASURB.MX', 'listing_home_label': 'ASUR B · MXN', 'listing_ads': 'ASR', 'listing_ads_label': 'ASR ADS · USD',
    'stmt_desc': bi('Elija dos periodos y compare el estado de resultados, el balance o el flujo de efectivo con variación absoluta y porcentual. Los modos <b>acumulado del año</b> (por ejemplo 6M26 vs 6M25) y <b>últimos doce meses</b> se construyen a partir de las cifras trimestrales reportadas. El interruptor IFRIC 12 excluye los ingresos y costos por servicios de construcción de activos concesionados (registrados a margen cero en México y Puerto Rico; en Colombia con un margen razonable), que distorsionan el margen EBITDA reportado. Debajo del estado de resultados se muestra el desglose por país (México, Puerto Rico, Colombia y Estados Unidos) tal como ASUR lo reporta.',
                    'Pick two periods and compare the income statement, balance sheet or cash-flow statement with absolute and percentage variances. The <b>year-to-date</b> mode (e.g. 6M26 vs 6M25) and <b>last-twelve-months</b> mode are built from the reported quarterly figures. The IFRIC 12 switch strips out construction-service revenue and cost on concession assets (booked at zero margin in Mexico and Puerto Rico; with a reasonable margin in Colombia), which distort the reported EBITDA margin. Below the income statement, the breakdown by country (Mexico, Puerto Rico, Colombia and the United States) is shown as ASUR reports it.'),
    'guide_desc': bi('ASUR no publica una tabla formal de guía anual (rangos de tráfico, ingresos o EBITDA). Lo que sí comunica son los compromisos de inversión del Programa Maestro de Desarrollo, el objetivo de cumplimiento de la tarifa máxima (≈99% al cierre del año) y comentarios cualitativos en cada conferencia de resultados. Esta sección muestra esos compromisos con su fuente; si ASUR empezara a publicar guía numérica, el flujo de datos la extraería automáticamente y aparecería aquí como en el modelo de GAP.',
                     'ASUR does not publish a formal annual guidance table (ranges for traffic, revenue or EBITDA). It does communicate the Master Development Program investment commitments, the maximum-tariff compliance objective (≈99% by year-end) and qualitative comments on each earnings call. This section shows those commitments with their source; if ASUR started publishing numerical guidance, the data pipeline would extract it automatically and it would appear here as in the GAP model.'),
    'traffic_desc': bi('Pasajeros (nacionales e internacionales) por aeropuerto y por país, según los reportes mensuales de tráfico de ASUR: nueve aeropuertos en el sureste de México (Cancún concentra unos siete de cada diez pasajeros mexicanos), San Juan de Puerto Rico (Aerostar, 60%) y seis aeropuertos en Colombia (Airplan). México y Colombia excluyen pasajeros en tránsito y aviación general; San Juan los incluye. Los 20 aeropuertos adquiridos a Motiva (Brasil, Ecuador, Costa Rica y Curazao) se añadirán cuando ASUR empiece a reportarlos.',
                       'Passengers (domestic and international) by airport and by country, from ASUR\'s monthly traffic reports: nine airports in south-east Mexico (Cancún carries about seven of every ten Mexican passengers), San Juan, Puerto Rico (Aerostar, 60%) and six airports in Colombia (Airplan). Mexico and Colombia exclude transit and general-aviation passengers; San Juan includes them. The 20 airports acquired from Motiva (Brazil, Ecuador, Costa Rica and Curaçao) will be added once ASUR reports them.'),
    'share_desc': bi('ASUR cotiza como serie B en la BMV (pesos) y como ADS en la NYSE (ASR, dólares; 1 ADS = 10 acciones B). El comparativo reindexa cada serie a 100 al inicio del periodo elegido para verla contra el S&amp;P/BMV IPC y los pares mexicanos GAP y OMA. Precios de cierre diarios; se actualizan cada día hábil.',
                     'ASUR trades as series B shares on the BMV (pesos) and as ADSs on the NYSE (ASR, dollars; 1 ADS = 10 B shares). The comparison rebases every series to 100 at the start of the chosen window to see it against the S&amp;P/BMV IPC and Mexican peers GAP and OMA. Daily closes, refreshed every business day.'),
    'dcf_desc': bi('Flujo de efectivo libre a la firma en pesos nominales durante cinco años explícitos, descontado a un WACC construido con CAPM sobre el bono mexicano a 10 años. Como las concesiones mexicanas vencen en 2048, el valor terminal por defecto es una <b>anualidad hasta el fin de la concesión</b>; Puerto Rico (arrendamiento a 40 años desde 2013), Colombia (concesión de Airplan, vigente hasta la década de 2030 según la Forma 20-F) y los activos de Motiva tienen otros horizontes, así que la fecha es editable. Todos los supuestos son editables y el resultado se recalcula al instante.',
                   'Unlevered free cash flow in nominal pesos over five explicit years, discounted at a CAPM-based WACC built on the Mexican 10-year bond. Because the Mexican concessions expire in 2048, the default terminal value is an <b>annuity to the end of the concession</b>; Puerto Rico (40-year lease from 2013), Colombia (the Airplan concession, running into the 2030s per the Form 20-F) and the Motiva assets have other horizons, so the year is editable. Every assumption is editable and the result recalculates instantly.'),
    'rel_desc': bi('Múltiplos de ASUR calculados en vivo con el precio más reciente, las acciones en circulación y las cifras de los últimos doce meses. La tabla de pares (GAP, OMA, Aena, Fraport, Zúrich, Auckland) se llenará automáticamente con el conector de FactSet cuando esté autorizado; mientras tanto muestra la estructura vacía.',
                   'ASUR multiples computed live from the latest price, shares outstanding and last-twelve-month figures. The peer table (GAP, OMA, Aena, Fraport, Zurich, Auckland) will be filled automatically by the FactSet connector once it is authorised; until then it shows the empty structure.'),
    'debt_desc': bi('Deuda neta (deuda financiera menos efectivo) y su relación con el EBITDA de los últimos doce meses, más los instrumentos vigentes: préstamos bancarios en pesos de Aeropuerto de Cancún (BBVA, Santander, JPMorgan), los bonos en dólares de Aerostar (Puerto Rico) y los créditos bancarios de Airplan en Colombia referenciados a la tasa DTF. La compra de Motiva (R$5.1 mil millones, US$992 millones) se financió con un crédito contratado al presentar la oferta (JPMorgan Chase comprometió el financiamiento al firmar) y aparecerá en el balance del 3T26.',
                    'Net debt (financial debt less cash) and its ratio to last-twelve-month EBITDA, plus the outstanding instruments: peso bank loans at Cancún Airport (BBVA, Santander, JPMorgan), Aerostar\'s dollar bonds (Puerto Rico) and Airplan\'s DTF-linked bank facilities in Colombia. The Motiva purchase (R$5.1 bn, US$992 million) was financed with a loan facility arranged when ASUR submitted its offer (JPMorgan Chase committed the financing at signing) and will appear on the 3Q26 balance sheet.'),
    'div_desc': bi('Dividendo por acción pagado cada año (efectivo por acción registrado en bolsa) y el aprobado por las asambleas más recientes: Ps. 10.00 ordinario (abril de 2026) más dos extraordinarios de Ps. 10.00 cada uno con cargo a la reserva de recompra (noviembre y diciembre de 2026); razón de pago contra la utilidad neta mayoritaria y rendimiento sobre el precio de cierre del año.',
                   'Dividend per share paid each year (exchange-recorded cash per share) and the amounts approved at the latest meetings: Ps. 10.00 ordinary (April 2026) plus two extraordinary dividends of Ps. 10.00 each charged to the buyback reserve (November and December 2026); payout ratio against majority net income and yield on the year-end price.'),
    'event_nav': 'Motiva · ASUR US', 'event_num': '09',
    'event_title': bi('Expansión: Motiva Airports y ASUR US Airports', 'Expansion: Motiva Airports and ASUR US Airports'),
    'event_prose': [
      bi('<b>Motiva Airports.</b> El 18 de noviembre de 2025 ASUR acordó comprar a Motiva Infraestrutura de Mobilidade (B3: MOTV3) el 100% de Companhia de Participações em Concessões (CPC), tenedora de participaciones en 20 aeropuertos: 17 en Brasil (Confins, Pampulha, los bloques Sul y Central), Quito (Ecuador), San José de Costa Rica (Juan Santamaría) y Curazao. Precio: R$5,000 millones (US$936 millones) por el capital, con un valor de empresa implícito de R$13,700 millones (US$2,566 millones); EBITDA de los doce meses a septiembre de 2025 de R$2,000 millones al 100% (R$1,300 millones proporcional a CPC) y deuda financiera neta de R$6,300 millones. La operación cerró el 1 de septiembre de 2026 por R$5,100 millones (US$992 millones) tras ajustes, financiada con el crédito contratado al presentar la oferta (JPMorgan Chase comprometió el financiamiento al firmar).',
         '<b>Motiva Airports.</b> On 18 November 2025 ASUR agreed to buy from Motiva Infraestrutura de Mobilidade (B3: MOTV3) 100% of Companhia de Participações em Concessões (CPC), which holds stakes in 20 airports: 17 in Brazil (Confins, Pampulha, the Sul and Central blocks), Quito (Ecuador), San José, Costa Rica (Juan Santamaría) and Curaçao. Price: R$5,000 million (US$936 million) for the equity, implying an enterprise value of R$13,700 million (US$2,566 million); EBITDA for the twelve months to September 2025 of R$2,000 million at 100% (R$1,300 million proportional to CPC) and net financial debt of R$6,300 million. The deal closed on 1 September 2026 for R$5,100 million (US$992 million) after adjustments, financed with the loan facility arranged when ASUR submitted its offer (JPMorgan Chase committed the financing at signing).'),
      bi('<b>ASUR US Airports.</b> En julio de 2025 ASUR acordó comprar a URW el negocio de concesiones comerciales en terminales de Los Ángeles (LAX), Chicago O\'Hare (T5) y Nueva York JFK (T8 y New Terminal One); cerró el 11 de diciembre de 2025. Es ingreso comercial en dólares, no regulado, que se consolida dentro de los ingresos no aeronáuticos (Ps. 444 millones en el 2T26) con un margen bajo mientras la plataforma madura: la transformación comercial de la Terminal 8 de JFK (US$125 millones) concluyó en abril de 2026 y la New Terminal One abre hacia el primer trimestre de 2027.',
         '<b>ASUR US Airports.</b> In July 2025 ASUR agreed to buy from URW the commercial-concession business at terminals in Los Angeles (LAX), Chicago O\'Hare (T5) and New York JFK (T8 and New Terminal One); it closed on 11 December 2025. It is dollar-denominated, unregulated commercial revenue consolidated within non-aeronautical revenue (Ps. 444 million in 2Q26) at a low margin while the platform matures: the US$125 million commercial transformation of JFK Terminal 8 finished in April 2026 and New Terminal One opens toward the first quarter of 2027.'),
      bi('<b>Qué cambia en el modelo.</b> Desde el 3T26 se consolidan 20 aeropuertos más (≈45 millones de pasajeros anuales frente a 71 millones reportados por ASUR en 2024), con ingresos en reales, dólares y colones, deuda adicional (el crédito de Motiva más la deuda neta de CPC) y un mayor peso de la participación no controladora. Los comparativos año contra año perderán homogeneidad durante cuatro trimestres; la sección de tráfico separa los aeropuertos heredados de los nuevos cuando ASUR empiece a reportarlos. Además, la asamblea del 20 de agosto de 2026 aprobó internalizar la asistencia técnica (fusión con ITA, ≈7.2 millones de acciones nuevas; 300 → ≈307.2 millones) y dos dividendos extraordinarios de Ps. 10.00.',
         '<b>What changes in the model.</b> From 3Q26 another 20 airports consolidate (≈45 million annual passengers versus the 71 million ASUR reported in 2024), with revenue in reais, dollars and colones, additional debt (the Motiva loan plus CPC\'s net debt) and a larger non-controlling interest. Year-over-year comparisons lose homogeneity for four quarters; the traffic section will separate legacy and new airports once ASUR reports them. The 20 August 2026 meeting also approved internalising technical assistance (merger with ITA, ≈7.2 million new shares; 300 → ≈307.2 million) and two extraordinary dividends of Ps. 10.00.'),
    ],
    'ex_nav': 'Aerostar · Airplan', 'ex_num': '10',
    'ex_title': bi('Puerto Rico y Colombia explicados', 'Puerto Rico and Colombia explained'),
    'ex_prose': [
      bi('<b>Aerostar (San Juan, Puerto Rico).</b> Aerostar Airport Holdings opera el aeropuerto Luis Muñoz Marín bajo un arrendamiento a 40 años desde 2013 (plazo según la Forma 20-F), la primera y única asociación público-privada de un aeropuerto grande en Estados Unidos concluida bajo el programa piloto de la FAA. ASUR posee el 60%; el 40% restante aparece como participación no controladora: por eso ASUR reporta "utilidad neta mayoritaria". La deuda de Aerostar son bonos en dólares (5.75%, 4.92% y 6.75%, con vencimiento en 2035; saldo US$486 millones al 30 de junio de 2026, Tabla 7).',
         '<b>Aerostar (San Juan, Puerto Rico).</b> Aerostar Airport Holdings operates Luis Muñoz Marín airport under a 40-year lease from 2013 (term per the Form 20-F), the first and only large-airport public–private partnership in the United States completed under the FAA pilot programme. ASUR owns 60%; the other 40% shows as non-controlling interest, which is why ASUR reports "majority net income". Aerostar\'s debt is dollar bonds (5.75%, 4.92% and 6.75%, due 2035; balance US$486 million at 30 June 2026, Table 7).'),
      bi('<b>Airplan (Colombia).</b> Sociedad concesionaria de seis aeropuertos del noroeste colombiano: Medellín–Rionegro (José María Córdova, el segundo del país), Olaya Herrera, Montería, Carepa, Quibdó y Corozal, adquirida en 2017 (92.4%). La Aeronáutica Civil fija las tarifas (Resolución 04530 de 2007, con su fórmula de actualización); bajo IFRIC 12 los ingresos por construcción en Colombia sí llevan un margen. En el 3T25 Airplan cambió el método de amortización de la concesión, lo que elevó la depreciación y explica buena parte de la caída de la utilidad de operación de Colombia desde entonces.',
         '<b>Airplan (Colombia).</b> The concession company for six airports in north-west Colombia: Medellín–Rionegro (José María Córdova, the country\'s second busiest), Olaya Herrera, Montería, Carepa, Quibdó and Corozal, acquired in 2017 (92.4%). The civil-aviation authority sets tariffs (Resolution 04530 of 2007 and its updating formula); under IFRIC 12 construction revenue in Colombia does carry a margin. In 3Q25 Airplan changed the concession amortisation method, which raised depreciation and explains much of the fall in Colombia\'s operating profit since then.'),
      bi('<b>Cómo leerlo en los estados financieros.</b> El estado de resultados consolida 100% de Puerto Rico y Colombia; la tabla por país muestra ingresos, EBITDA y utilidad de cada uno. Las cifras en dólares y pesos colombianos se convierten a pesos mexicanos al tipo de cambio promedio del periodo, de modo que un peso mexicano fuerte reduce el crecimiento reportado de esas operaciones aunque en moneda local crezcan.',
         '<b>Reading it in the statements.</b> The income statement consolidates 100% of Puerto Rico and Colombia; the table by country shows each one\'s revenue, EBITDA and net income. Dollar and Colombian-peso figures are converted to Mexican pesos at the period\'s average rate, so a strong Mexican peso lowers the reported growth of those operations even when they grow in local currency.'),
    ],
    'method_ifric': bi('<b>IFRIC 12.</b> Bajo IFRS, el operador de una concesión registra las obras que construye para el concedente como ingreso por servicios de construcción y, al mismo tiempo, como costo (a margen cero en México y Puerto Rico; en Colombia con un margen) y como activo intangible. Por eso el margen EBITDA "reportado" de ASUR baja cuando invierte más (2T26: 47.9% reportado frente a 62.0% ajustado). La vista sin IFRIC 12 resta ese ingreso y ese costo; el EBITDA no cambia, el margen sí.',
                       '<b>IFRIC 12.</b> Under IFRS, a concession operator books the works it builds for the grantor as construction-service revenue and, simultaneously, as cost (at zero margin in Mexico and Puerto Rico; with a margin in Colombia) and as an intangible asset. That is why ASUR\'s "reported" EBITDA margin falls when it invests more (2Q26: 47.9% reported versus 62.0% adjusted). The ex-IFRIC 12 view removes that revenue and cost; EBITDA is unchanged, the margin is not.'),
    'method_ytd': bi('<b>Acumulado y UDM.</b> El acumulado del año usa las columnas de tres, seis, nueve o doce meses del informe trimestral de ASUR (que reporta el estado de resultados en ambas bases y el flujo de efectivo solo acumulado; el flujo trimestral se obtiene por diferencia); los últimos doce meses suman los cuatro trimestres más recientes. El balance siempre es al cierre del periodo.',
                     '<b>Year-to-date and LTM.</b> Year-to-date uses the three-, six-, nine- or twelve-month columns of ASUR\'s quarterly report (which prints the income statement on both bases and the cash flow year-to-date only; the quarterly cash flow is the difference); last-twelve-months adds the four most recent quarters. The balance sheet is always the period-end position.'),
    'method_dcf': bi('<b>DCF.</b> FCF = EBITDA − impuestos sobre la utilidad operativa − capex − Δ capital de trabajo. WACC = E/(D+E)·[Rf + β·ERP] + D/(D+E)·Kd·(1−t), con Rf = bono M a 10 años y β calculada con dos años de rendimientos semanales de ASUR B contra el IPC. Valor terminal por anualidad hasta el fin de la concesión, por perpetuidad o por múltiplo. Valor del capital = VE − deuda neta − participación no controladora (valor en libros, principalmente el 40% de Aerostar). Es una herramienta de sensibilidad, no una recomendación.',
                     '<b>DCF.</b> FCF = EBITDA − taxes on operating profit − capex − Δ working capital. WACC = E/(D+E)·[Rf + β·ERP] + D/(D+E)·Kd·(1−t), with Rf = the 10-year M bond and β computed from two years of weekly ASUR B returns against the IPC. Terminal value by annuity to the concession end, perpetuity or multiple. Equity value = EV − net debt − non-controlling interest (book value, mainly the 40% of Aerostar). It is a sensitivity tool, not a recommendation.'),
    'method_flow': bi('Flujo de datos: <code>scripts/asur/*</code>, <code>scripts/airports/*</code> y <code>.github/workflows/asur-refresh.yml</code> en el repositorio; runbook en <code>tools/asur/README.md</code>.', 'Data flow: <code>scripts/asur/*</code>, <code>scripts/airports/*</code> and <code>.github/workflows/asur-refresh.yml</code> in the repository; runbook in <code>tools/asur/README.md</code>.'),
    'fine': bi('Este modelo se elabora exclusivamente con información pública (informes trimestrales, comunicados y transcripciones de conferencias de ASUR; Formas 20-F; precios de mercado; series de FRED). No contiene ni debe alimentarse con información privilegiada. Las proyecciones del DCF son ilustrativas y dependen de los supuestos elegidos por la persona usuaria; no constituyen una recomendación de inversión. Cifras en pesos mexicanos nominales salvo indicación. Última generación de datos: <span class="genStamp"></span>.',
               'This model is built exclusively from public information (ASUR\'s quarterly reports, releases and earnings-call transcripts; Forms 20-F; market prices; FRED series). It contains, and must not be fed, any material non-public information. DCF projections are illustrative and depend on the user\'s assumptions; they are not an investment recommendation. Figures in nominal Mexican pesos unless stated. Data last generated: <span class="genStamp"></span>.'),
    'margin_title': bi('Margen EBITDA ajustado (sin IFRIC 12)', 'Adjusted EBITDA margin (ex-IFRIC 12)'), 'margin_cap': bi('EBITDA / (ingresos − ingresos por construcción), %', 'EBITDA / (revenue − construction revenue), %'),
    'has_segments': True,
  },
  'oma': {
    'prefix': 'OMA', 'short': 'OMA', 'name': 'Grupo Aeroportuario del Centro Norte', 'title_es': 'OMA · Modelo financiero interactivo | Grupo Aeroportuario del Centro Norte',
    'desc_es': 'Modelo financiero interactivo de Grupo Aeroportuario del Centro Norte (OMA): estados financieros comparables por trimestre, tráfico de pasajeros en 13 aeropuertos, acción, DCF y valuación relativa. Datos públicos.',
    'eyebrow_es': 'Modelo financiero interactivo · Datos públicos (BMV / Nasdaq / SEC)', 'eyebrow_en': 'Interactive financial model · Public data (BMV / Nasdaq / SEC)',
    'listing_home': 'OMAB.MX', 'listing_home_label': 'OMA B · MXN', 'listing_ads': 'OMAB', 'listing_ads_label': 'OMAB ADS · USD',
    'stmt_desc': bi('Elija dos periodos y compare el estado de resultados, el balance o el flujo de efectivo con variación absoluta y porcentual. Los modos <b>acumulado del año</b> y <b>últimos doce meses</b> se construyen a partir de las cifras trimestrales reportadas. El interruptor IFRIC 12 excluye los ingresos y costos por construcción de activos concesionados (a margen cero). OMA reporta un <b>EBITDA ajustado</b> (EBITDA reportado − ingresos por construcción + costos de construcción + provisión de mantenimiento mayor) y su margen sobre ingresos aeronáuticos + no aeronáuticos; esa es la medida que usa este modelo, con el EBITDA reportado como renglón adicional. Los ingresos aeronáuticos (TUA nacional e internacional), los no aeronáuticos (comerciales, diversificación, complementarios) y los costos de servicios se desglosan en grupos plegables.',
                    'Pick two periods and compare the income statement, balance sheet or cash-flow statement with absolute and percentage variances. The <b>year-to-date</b> and <b>last-twelve-months</b> modes are built from the reported quarterly figures. The IFRIC 12 switch strips out construction revenue and cost on concession assets (zero margin). OMA reports an <b>Adjusted EBITDA</b> (reported EBITDA − construction revenue + construction cost + major-maintenance provision) and its margin over aeronautical + non-aeronautical revenue; that is the measure this model uses, with reported EBITDA as an extra line. Aeronautical revenue (domestic and international TUA), non-aeronautical revenue (commercial, diversification, complementary) and the cost of services are broken down in collapsible groups.'),
    'guide_desc': bi('OMA no publica una tabla formal de guía anual. Lo que sí comunica son los compromisos de inversión del Programa Maestro de Desarrollo (PMD) 2026–2030 aprobado en diciembre de 2025, la tarifa máxima por unidad de tráfico para el quinquenio y comentarios cualitativos sobre tráfico, márgenes y capex en cada conferencia de resultados. Esta sección muestra esos compromisos con su fuente; si OMA empezara a publicar guía numérica, el flujo de datos la extraería automáticamente.',
                     'OMA does not publish a formal annual guidance table. It does communicate the 2026–2030 Master Development Program (MDP) investment commitments approved in December 2025, the maximum tariff per traffic unit for the five-year period and qualitative comments on traffic, margins and capex on each earnings call. This section shows those commitments with their source; if OMA started publishing numerical guidance, the data pipeline would extract it automatically.'),
    'traffic_desc': bi('Pasajeros terminales (nacionales e internacionales) por aeropuerto, según los reportes mensuales de tráfico de OMA: 13 aeropuertos en nueve estados del centro y norte de México, con Monterrey como eje (más de la mitad del tráfico), tres destinos turísticos (Acapulco, Mazatlán y Zihuatanejo) y nueve ciudades regionales y fronterizas. Incluye aviación comercial, chárter y general; excluye pasajeros en tránsito. Vea la serie mensual, trimestral o anual y compare contra el mismo periodo del año anterior.',
                       'Terminal passengers (domestic and international) by airport, from OMA\'s monthly traffic reports: 13 airports in nine states of central and northern Mexico, with Monterrey as the hub (over half of traffic), three tourist destinations (Acapulco, Mazatlán and Zihuatanejo) and nine regional and border cities. Includes commercial, charter and general aviation; excludes transit passengers. View the monthly, quarterly or annual series and compare with the same period a year earlier.'),
    'share_desc': bi('OMA cotiza como serie B en la BMV (pesos) y como ADS en el Nasdaq (OMAB, dólares; 1 ADS = 8 acciones B). Desde diciembre de 2022 OMA forma parte de VINCI Airports, que tiene una participación indirecta de 29.99%. El comparativo reindexa cada serie a 100 al inicio del periodo elegido para verla contra el S&amp;P/BMV IPC y los pares mexicanos GAP y ASUR. Precios de cierre diarios; se actualizan cada día hábil.',
                     'OMA trades as series B shares on the BMV (pesos) and as ADSs on Nasdaq (OMAB, dollars; 1 ADS = 8 B shares). Since December 2022 OMA is part of VINCI Airports, which holds an indirect 29.99% stake. The comparison rebases every series to 100 at the start of the chosen window to see it against the S&amp;P/BMV IPC and Mexican peers GAP and ASUR. Daily closes, refreshed every business day.'),
    'dcf_desc': bi('Flujo de efectivo libre a la firma en pesos nominales durante cinco años explícitos, descontado a un WACC construido con CAPM sobre el bono mexicano a 10 años. Como las 13 concesiones vencen en 2048, el valor terminal por defecto es una <b>anualidad hasta el fin de la concesión</b>, no una perpetuidad; puede cambiarlo a perpetuidad o a múltiplo de salida. El EBITDA base es el ajustado (excluye la provisión de mantenimiento mayor, que sí es un desembolso futuro: el capex del modelo debe incluirla). Todos los supuestos son editables.',
                   'Unlevered free cash flow in nominal pesos over five explicit years, discounted at a CAPM-based WACC built on the Mexican 10-year bond. Because the 13 concessions expire in 2048, the default terminal value is an <b>annuity to the end of the concession</b>, not a perpetuity; switch to perpetuity or an exit multiple if you prefer. The base EBITDA is the adjusted one (it excludes the major-maintenance provision, which is a real future outlay: the model\'s capex should include it). Every assumption is editable.'),
    'rel_desc': bi('Múltiplos de OMA calculados en vivo con el precio más reciente, las 386.2 millones de acciones en circulación y las cifras de los últimos doce meses (EBITDA ajustado). La tabla de pares (GAP, ASUR, Aena, Fraport, Zúrich, Auckland) se llenará automáticamente con el conector de FactSet cuando esté autorizado; mientras tanto muestra la estructura vacía.',
                   'OMA multiples computed live from the latest price, the 386.2 million shares outstanding and last-twelve-month figures (Adjusted EBITDA). The peer table (GAP, ASUR, Aena, Fraport, Zurich, Auckland) will be filled automatically by the FactSet connector once it is authorised; until then it shows the empty structure.'),
    'debt_desc': bi('Deuda neta (deuda financiera menos efectivo) y su relación con el EBITDA ajustado de los últimos doce meses, más los instrumentos vigentes: certificados bursátiles en pesos a tasa fija y variable (varios ligados a sostenibilidad), tomados directamente de la tabla de deuda que OMA publica cada trimestre, y líneas bancarias de corto plazo. La emisión de Ps. 3,000 millones de julio de 2026 refinanció el crédito de Ps. 1,700 millones y el OMA 23L.',
                    'Net debt (financial debt less cash) and its ratio to last-twelve-month Adjusted EBITDA, plus the outstanding instruments: peso certificados bursátiles at fixed and floating rates (several sustainability-linked), taken directly from the debt table OMA publishes every quarter, and short-term bank lines. The Ps. 3,000 million issuance of July 2026 refinanced the Ps. 1,700 million loan and OMA 23L.'),
    'div_desc': bi('Dividendo por acción pagado cada año (efectivo por acción registrado en bolsa) y el aprobado por la asamblea más reciente (Ps. 4,900 millones en abril de 2026, en dos exhibiciones: la de mayo se registró en bolsa a Ps. 6.28 por acción); razón de pago contra la utilidad neta de la participación controladora y rendimiento sobre el precio de cierre del año.',
                   'Dividend per share paid each year (exchange-recorded cash per share) and the amount approved at the latest AGM (Ps. 4,900 million in April 2026, in two instalments: the May one was recorded by the exchange at Ps. 6.28 per share); payout ratio against net income of the controlling interest and yield on the year-end price.'),
    'event_nav': 'PMD 2026–2030', 'event_num': '09',
    'event_title': bi('Programa Maestro de Desarrollo 2026–2030 y tarifa máxima', 'Master Development Program 2026–2030 and maximum tariff'),
    'event_prose': [
      bi('<b>Qué es.</b> Cada cinco años la Secretaría de Infraestructura, Comunicaciones y Transportes (SICT) y la Agencia Federal de Aviación Civil aprueban para cada aeropuerto concesionado un Programa Maestro de Desarrollo (PMD): el plan de inversiones y mantenimiento mayor que el concesionario se compromete a ejecutar, y la <b>tarifa máxima</b> por unidad de tráfico que puede cobrar por los servicios regulados (TUA, aterrizajes, estacionamiento de aeronaves, arrendamientos regulados). La tarifa se fija en pesos constantes y se ajusta por inflación y por un factor de eficiencia; el cumplimiento se revisa anualmente.',
         '<b>What it is.</b> Every five years the Ministry of Infrastructure, Communications and Transport (SICT) and the Federal Civil Aviation Agency approve, for each concessioned airport, a Master Development Program (MDP): the investment and major-maintenance plan the concessionaire commits to execute, and the <b>maximum tariff</b> per traffic unit it may charge for regulated services (TUA, landings, aircraft parking, regulated leases). The tariff is set in constant pesos and adjusted for inflation and an efficiency factor; compliance is reviewed annually.'),
      bi('<b>El PMD 2026–2030.</b> Aprobado por la SICT/AFAC el 18 de diciembre de 2025 para los 13 aeropuertos de OMA: Ps. 16,005 millones en pesos de diciembre de 2024, la mitad en Monterrey, con prioridad en la ampliación y modernización de terminales, infraestructura aeronáutica, equipo y tecnología y sostenibilidad; incluye el mantenimiento mayor (que OMA provisiona en resultados y reversa en el EBITDA ajustado). El monto comprometido por año y aeropuerto y las tarifas máximas 2026–2030 se toman del comunicado de OMA del 18 de diciembre de 2025 (ficha y cronología abajo).',
         '<b>The 2026–2030 MDP.</b> Approved by SICT/AFAC on 18 December 2025 for OMA\'s 13 airports: Ps. 16,005 million in December-2024 pesos, half of it at Monterrey, prioritising terminal expansion and modernisation, airfield infrastructure, equipment and technology and sustainability; it includes major maintenance (which OMA provisions through the income statement and adds back in Adjusted EBITDA). The committed amount by year and airport and the 2026–2030 maximum tariffs are taken from OMA\'s 18 December 2025 release (fact sheet and timeline below).'),
      bi('<b>Qué cambia en el modelo.</b> El capex del DCF sigue el perfil del PMD; los ingresos por construcción (IFRIC 12) subirán con la ejecución de obra sin afectar el EBITDA ajustado; la provisión de mantenimiento mayor crece con el nuevo programa (Ps. 99 millones en el 2T26 frente a Ps. 50 millones un año antes). Las tarifas máximas bajan 0.8% real al año (factor de eficiencia), así que el crecimiento de la TUA por pasajero depende de la inflación y de la mezcla doméstico/internacional.',
         '<b>What changes in the model.</b> DCF capex follows the MDP profile; construction revenue (IFRIC 12) will rise with execution without affecting Adjusted EBITDA; the major-maintenance provision grows with the new program (Ps. 99 million in 2Q26 versus Ps. 50 million a year earlier). Maximum tariffs fall 0.8% a year in real terms (efficiency factor), so TUA growth per passenger depends on inflation and the domestic/international mix.'),
    ],
    'ex_nav': 'VINCI', 'ex_num': '10',
    'ex_title': bi('VINCI Airports y los bonos ligados a sostenibilidad', 'VINCI Airports and the sustainability-linked bonds'),
    'ex_prose': [
      bi('<b>El accionista estratégico.</b> El 31 de julio de 2022 Fintech Advisory anunció la venta de su participación indirecta de 29.99% en OMA a VINCI Airports; el cierre se comunicó el 7 de diciembre de 2022 (informe 4T22). Desde entonces OMA se describe como parte de VINCI Airports y paga a su socio estratégico una cuota de asistencia técnica calculada sobre el EBITDA (Ps. 69.0 millones en el 2T26, +2.9%). El resto del capital cotiza en la BMV (serie B) y como ADS en el Nasdaq (1 ADS = 8 acciones).',
         '<b>The strategic shareholder.</b> On 31 July 2022 Fintech Advisory announced the sale of its indirect 29.99% stake in OMA to VINCI Airports; the closing was reported on 7 December 2022 (4Q22 report). Since then OMA describes itself as part of VINCI Airports and pays its strategic partner a technical-assistance fee computed on EBITDA (Ps. 69.0 million in 2Q26, +2.9%). The rest of the capital trades on the BMV (series B) and as ADSs on Nasdaq (1 ADS = 8 shares).'),
      bi('<b>Bonos ligados a sostenibilidad.</b> Cuatro certificados bursátiles de OMA (OMA 22L, OMA 22-2L, OMA 23L y OMA 23-2L) llevan un objetivo de desempeño en sostenibilidad (SPT): reducir 58% las emisiones de gases de efecto invernadero de alcances 1 y 2 por pasajero (kgCO2e/PAX) al 31 de diciembre de 2025 frente a 2018. El 25 de junio de 2026 OMA anunció que alcanzó una reducción de 88%, por encima de la meta.',
         '<b>Sustainability-linked bonds.</b> Four OMA certificados bursátiles (OMA 22L, OMA 22-2L, OMA 23L and OMA 23-2L) carry a sustainability performance target (SPT): a 58% cut in scope 1 and 2 greenhouse-gas emissions per passenger (kgCO2e/PAX) by 31 December 2025 versus 2018. On 25 June 2026 OMA announced an 88% reduction, above the target.'),
      bi('<b>Cómo leerlo.</b> La participación no controladora es pequeña (Ps. 11.1 millones de la utilidad del 2T26; Ps. 184 millones en el balance), así que la utilidad de la participación controladora es casi toda la utilidad consolidada. OMA reporta su apalancamiento como deuda neta (incluidos arrendamientos) / EBITDA ajustado de los últimos doce meses: 1.13x al 30 de junio de 2026.',
         '<b>Reading it.</b> The non-controlling interest is small (Ps. 11.1 million of 2Q26 net income; Ps. 184 million on the balance sheet), so net income of the controlling interest is almost all of consolidated net income. OMA reports its leverage as net debt (including leases) / last-twelve-month Adjusted EBITDA: 1.13x at 30 June 2026.'),
    ],
    'method_ifric': bi('<b>IFRIC 12 y EBITDA ajustado.</b> Bajo IFRS, el operador de una concesión registra las obras que construye para el concedente como ingreso por construcción y como costo por el mismo importe (margen cero) y como activo intangible. OMA además reconoce en resultados la provisión de mantenimiento mayor. Su EBITDA ajustado = EBITDA − ingresos por construcción + costos de construcción + provisión de mantenimiento mayor, con margen sobre ingresos aeronáuticos + no aeronáuticos (2T26: 75.2% ajustado frente a 58.7% reportado). Es la medida de este modelo.',
                       '<b>IFRIC 12 and Adjusted EBITDA.</b> Under IFRS, a concession operator books the works it builds for the grantor as construction revenue and as cost for the same amount (zero margin) and as an intangible asset. OMA also expenses the major-maintenance provision. Its Adjusted EBITDA = EBITDA − construction revenue + construction cost + major-maintenance provision, with the margin over aeronautical + non-aeronautical revenue (2Q26: 75.2% adjusted versus 58.7% reported). It is the measure this model uses.'),
    'method_ytd': bi('<b>Acumulado y UDM.</b> El acumulado del año usa las columnas de seis, nueve o doce meses del informe trimestral de OMA (que reporta cada estado en ambas bases); los últimos doce meses suman los cuatro trimestres más recientes. El balance siempre es al cierre del periodo; OMA lo compara con el mismo trimestre del año anterior y con diciembre.',
                     '<b>Year-to-date and LTM.</b> Year-to-date uses the six-, nine- or twelve-month columns of OMA\'s quarterly report (which prints every statement on both bases); last-twelve-months adds the four most recent quarters. The balance sheet is always the period-end position; OMA compares it with the same quarter a year earlier and with December.'),
    'method_dcf': bi('<b>DCF.</b> FCF = EBITDA ajustado − impuestos sobre la utilidad operativa − capex (incluido mantenimiento mayor) − Δ capital de trabajo. WACC = E/(D+E)·[Rf + β·ERP] + D/(D+E)·Kd·(1−t), con Rf = bono M a 10 años, β calculada con dos años de rendimientos semanales de OMA B contra el IPC y Kd = cupón del último certificado a tasa fija. Valor terminal por anualidad hasta 2048, por perpetuidad o por múltiplo. Valor del capital = VE − deuda neta − participación no controladora. Es una herramienta de sensibilidad, no una recomendación.',
                     '<b>DCF.</b> FCF = Adjusted EBITDA − taxes on operating profit − capex (including major maintenance) − Δ working capital. WACC = E/(D+E)·[Rf + β·ERP] + D/(D+E)·Kd·(1−t), with Rf = the 10-year M bond, β computed from two years of weekly OMA B returns against the IPC and Kd = the coupon of the latest fixed-rate bond. Terminal value by annuity to 2048, perpetuity or multiple. Equity value = EV − net debt − non-controlling interest. It is a sensitivity tool, not a recommendation.'),
    'method_flow': bi('Flujo de datos: <code>scripts/oma/*</code>, <code>scripts/airports/*</code> y <code>.github/workflows/oma-refresh.yml</code> en el repositorio; runbook en <code>tools/oma/README.md</code>.', 'Data flow: <code>scripts/oma/*</code>, <code>scripts/airports/*</code> and <code>.github/workflows/oma-refresh.yml</code> in the repository; runbook in <code>tools/oma/README.md</code>.'),
    'fine': bi('Este modelo se elabora exclusivamente con información pública (informes trimestrales, reportes de tráfico y comunicados de OMA; Formas 20-F; precios de mercado; series de FRED). No contiene ni debe alimentarse con información privilegiada. Las proyecciones del DCF son ilustrativas y dependen de los supuestos elegidos por la persona usuaria; no constituyen una recomendación de inversión. Cifras en pesos mexicanos nominales salvo indicación. Última generación de datos: <span class="genStamp"></span>.',
               'This model is built exclusively from public information (OMA\'s quarterly reports, traffic reports and releases; Forms 20-F; market prices; FRED series). It contains, and must not be fed, any material non-public information. DCF projections are illustrative and depend on the user\'s assumptions; they are not an investment recommendation. Figures in nominal Mexican pesos unless stated. Data last generated: <span class="genStamp"></span>.'),
    'margin_title': bi('Margen EBITDA ajustado', 'Adjusted EBITDA margin'), 'margin_cap': bi('EBITDA ajustado / (ingresos aeronáuticos + no aeronáuticos), %', 'Adjusted EBITDA / (aeronautical + non-aeronautical revenue), %'),
    'has_segments': False,
  },
}

def build(slug, c):
    s = gap
    # CSS: room for the fixed language toggle over the sticky nav; no print button on phones; stacked fact tables on phones
    s = s.replace('nav.jump .wrap{display:flex; gap:4px; overflow-x:auto; scrollbar-width:none;}', 'nav.jump .wrap{display:flex; gap:4px; overflow-x:auto; scrollbar-width:none; padding-right:300px;}\n@media (max-width:640px){nav.jump .wrap{padding-right:110px;} .lang-btn .print-btn{display:none;}}\n@media (max-width:640px){table.stack-sm, table.stack-sm tbody, table.stack-sm tr, table.stack-sm td{display:block; width:100%; box-sizing:border-box;} table.stack-sm thead{display:none;} table.stack-sm tr{padding:8px 0; border-bottom:1px solid var(--border);} table.stack-sm td{border:none; padding:2px 0; text-align:left !important;} table.stack-sm td:first-child{font-weight:600; color:var(--text-primary);}}\n#instrTable table{min-width:760px;} #instrTable td:first-child{min-width:220px;}')
    assert 'padding-right:300px' in s
    s = s.replace('<button type="button" data-v="max">Máx</button>', '<button type="button" data-v="max"><span class="es">Máx</span><span class="en" hidden>Max</span></button>')
    # head
    s = s.replace('<title>GAP · Modelo financiero interactivo | Grupo Aeroportuario del Pacífico</title>', f'<title>{c["title_es"]}</title>')
    s = re.sub(r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{c["desc_es"]}">', s)
    s = s.replace('<!-- Data files. Each is refreshed on its own cadence by .github/workflows/gap-refresh.yml\n     (market: daily · financials/traffic: after each release) or by reviewed PR (reference, peers). -->',
                  f'<!-- Data files. Each is refreshed on its own cadence by .github/workflows/{slug}-refresh.yml\n     (market: daily · financials/traffic: after each release) or by the reviewing routine (reference, comments, summary). -->')
    s = s.replace('<script src="data/peers.js"></script>', '<script src="data/peers.js"></script>\n<script src="config.js"></script>')
    s = s.replace('<script src="app.js"></script>', '<script src="../assets/airport-model.js"></script>')
    # header
    s = s.replace('<span class="es">Modelo financiero interactivo · Datos públicos (BMV / SEC)</span>\n      <span class="en" hidden>Interactive financial model · Public data (BMV / SEC)</span>', f'<span class="es">{c["eyebrow_es"]}</span>\n      <span class="en" hidden>{c["eyebrow_en"]}</span>')
    s = s.replace('<h1>Grupo Aeroportuario del Pacífico <span class="muted" style="font-weight:600">(GAP)</span></h1>', f'<h1>{c["name"]} <span class="muted" style="font-weight:600">({c["short"]})</span></h1>')
    # nav
    s = s.replace('<a href="#cbx">CBX</a>\n    <a href="#fibra">FIBRA GAP</a>', f'<a href="#event">{c["event_nav"]}</a>\n    <a href="#explainer">{c["ex_nav"]}</a>')
    # section descriptions
    def swap_desc(section_id, new_html):
        nonlocal s
        m = re.search(r'(<section class="block" id="%s">.*?<p class="sec-desc">\n)(.*?)(\n    </p>)' % section_id, s, re.S)
        assert m, section_id
        s = s[:m.start(2)] + '      ' + new_html + s[m.end(2):]
    swap_desc('statements', c['stmt_desc']); swap_desc('guidance', c['guide_desc']); swap_desc('traffic', c['traffic_desc']); swap_desc('share', c['share_desc'])
    swap_desc('dcf', c['dcf_desc']); swap_desc('relative', c['rel_desc']); swap_desc('debt', c['debt_desc']); swap_desc('dividends', c['div_desc'])
    # guidance: hide the guidance-only cards when no vintages exist (engine toggles .only-with-guidance)
    s = s.replace('<details class="tbl" id="guideTextWrap">', '<details class="tbl only-with-guidance" id="guideTextWrap">')
    s = s.replace('<span class="es">Supuestos citados por GAP (texto original en inglés)</span><span class="en" hidden>Assumptions in GAP\'s own words</span>', f'<span class="es">Supuestos citados por {c["short"]} (texto original en inglés)</span><span class="en" hidden>Assumptions in {c["short"]}\'s own words</span>')
    s = s.replace('<div class="card" style="margin-top:20px">\n      <h3><span class="es">Historial: últimos seis trimestres</span>', '<div class="card only-with-guidance" style="margin-top:20px">\n      <h3><span class="es">Historial: últimos seis trimestres</span>')
    s = s.replace('<div class="card" style="margin-top:20px">\n        <h3><span class="es">Guía vs. real por año</span>', '<div class="card only-with-guidance" style="margin-top:20px">\n        <h3><span class="es">Guía vs. real por año</span>')
    s = s.replace('<div class="card" style="margin-top:20px">\n        <h3><span class="es">Cumplimiento por año</span>', '<div class="card only-with-guidance" style="margin-top:20px">\n        <h3><span class="es">Cumplimiento por año</span>')
    s = s.replace('<details class="tbl" id="guideAllWrap">', '<details class="tbl only-with-guidance" id="guideAllWrap">')
    # margin chart title/caption + segments card
    s = s.replace('<h3><span class="es">Margen EBITDA sin IFRIC 12</span><span class="en" hidden>EBITDA margin ex-IFRIC 12</span></h3>\n        <p class="cap"><span class="es">EBITDA / (ingresos − ingresos por construcción), %</span><span class="en" hidden>EBITDA / (revenue − construction revenue), %</span></p>',
                  f'<h3>{c["margin_title"]}</h3>\n        <p class="cap">{c["margin_cap"]}</p>')
    s = s.replace('<span class="es">Fuente: informes trimestrales de GAP (margen reportado)</span><span class="en" hidden>Source: GAP quarterly reports (reported margin)</span>', f'<span class="es">Fuente: informes trimestrales de {c["short"]} (margen reportado)</span><span class="en" hidden>Source: {c["short"]} quarterly reports (reported margin)</span>')
    if c['has_segments']:
        s = s.replace('    <div class="grid-2 eq">\n      <div class="card">\n        <h3><span class="es">Ingresos por tipo</span>',
                      '    <div class="card" style="margin-top:20px">\n      <h3><span class="es">Resultados por país</span><span class="en" hidden>Results by country</span></h3>\n      <p class="cap"><span class="es">Ps. millones (miles convertidos), tal como ASUR reporta cada segmento; Puerto Rico y Colombia convertidos al tipo de cambio promedio del periodo; misma comparación A vs B que arriba</span><span class="en" hidden>Ps. million, as ASUR reports each segment; Puerto Rico and Colombia converted at the period average rate; same A vs B comparison as above</span></p>\n      <div class="tblwrap" id="segTable"></div>\n    </div>\n    <div class="grid-2 eq">\n      <div class="card">\n        <h3><span class="es">Ingresos por tipo</span>')
    # share listing buttons + rebased caption
    s = s.replace('<button type="button" data-v="GAPB.MX" class="active">GAP B · MXN</button>\n          <button type="button" data-v="PAC">PAC ADS · USD</button>', f'<button type="button" data-v="{c["listing_home"]}" class="active">{c["listing_home_label"]}</button>\n          <button type="button" data-v="{c["listing_ads"]}">{c["listing_ads_label"]}</button>')
    peers_es = {'asur': 'GAP B y OMA B', 'oma': 'GAP B y ASUR B'}[slug]
    s = s.replace('<span class="es">GAP B vs. S&amp;P/BMV IPC, ASUR B y OMA B, precio en pesos</span><span class="en" hidden>GAP B vs. S&amp;P/BMV IPC, ASUR B and OMA B, peso prices</span>', f'<span class="es">{c["short"]} B vs. S&amp;P/BMV IPC, {peers_es}, precio en pesos</span><span class="en" hidden>{c["short"]} B vs. S&amp;P/BMV IPC, {peers_es.replace(" y ", " and ")}, peso prices</span>')
    s = s.replace('<h3><span class="es">GAP: múltiplos actuales</span><span class="en" hidden>GAP: current multiples</span></h3>', f'<h3><span class="es">{c["short"]}: múltiplos actuales</span><span class="en" hidden>{c["short"]}: current multiples</span></h3>')
    # special sections: replace the CBX + FIBRA sections wholesale
    start = s.index('  <!-- 08 CBX -->'); end = s.index('  <!-- 10 METHOD -->')
    prose = lambda ps: ''.join(f'          <p>{p}</p>\n' for p in ps)
    special = f'''  <!-- 09 SPECIAL SITUATION -->
  <section class="block" id="event">
    <div class="sec-head"><span class="sec-num">{c["event_num"]}</span><h2>{c["event_title"]}</h2></div>
    <div class="grid-2">
      <div>
        <div class="prose">
{prose(c["event_prose"])}        </div>
        <div class="fact-grid" id="evFacts"></div>
      </div>
      <div class="card">
        <h3><span class="es">Cronología</span><span class="en" hidden>Timeline</span></h3>
        <ul class="timeline" id="evTimeline"></ul>
        <p class="chart-src" id="eventSrc"></p>
      </div>
    </div>
  </section>

  <!-- 10 EXPLAINER -->
  <section class="block" id="explainer">
    <div class="sec-head"><span class="sec-num">{c["ex_num"]}</span><h2>{c["ex_title"]}</h2></div>
    <div class="grid-2">
      <div class="prose">
{prose(c["ex_prose"])}        <div class="notice warn" id="exStatus"></div>
      </div>
      <div class="card">
        <h3><span class="es">Ficha</span><span class="en" hidden>Fact sheet</span></h3>
        <div class="tblwrap" id="exTable"></div>
        <p class="chart-src" id="exSrc"></p>
      </div>
    </div>
  </section>

'''
    s = s[:start] + special + s[end:]
    # method prose
    m = re.search(r'(<section class="block" id="method">.*?<div class="prose">\n)(.*?)(\n      </div>\n      <div class="card">)', s, re.S)
    s = s[:m.start(2)] + f'        <p>{c["method_ifric"]}</p>\n        <p>{c["method_ytd"]}</p>\n        <p>{c["method_dcf"]}</p>' + s[m.end(2):]
    s = re.sub(r'<p class="chart-src"><span class="es">Flujo de datos:.*?</span></p>', f'<p class="chart-src">{c["method_flow"]}</p>', s, flags=re.S)
    m = re.search(r'(<p class="fine">\n)(.*?)(\n    </p>)', s, re.S)
    s = s[:m.start(2)] + '      ' + c['fine'] + s[m.end(2):]
    assert 'GAP' not in re.sub(r'GAP B|GAP\b[^<]{0,3}(?=[,y ]| and)', '', s.split('<body>')[1]).replace('modelo de GAP', '').replace('GAP model', ''), [l for l in s.split('<body>')[1].splitlines() if 'GAP' in l][:8]
    out = os.path.join(ROOT, 'site', slug, 'index.html')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, 'w', encoding='utf-8').write(s)
    print(slug, 'written', len(s.splitlines()), 'lines')

for slug, c in COMPANIES.items():
    build(slug, c)
